USE AdventureWorks2022;
GO

CREATE TABLE Prueba (
    Id INT
);

INSERT INTO Prueba (Id) VALUES (CAST(RAND()*100 AS INT));
INSERT INTO Prueba (Id) VALUES (CAST(RAND()*100 AS INT));
INSERT INTO Prueba (Id) VALUES (CAST(RAND()*100 AS INT));
INSERT INTO Prueba (Id) VALUES (CAST(RAND()*100 AS INT));
INSERT INTO Prueba (Id) VALUES (CAST(RAND()*100 AS INT));
